all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    db_host: "{{ lookup('env', 'DB_HOST') }}"
    db_port: "{{ lookup('env', 'DB_PORT') }}"
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
